version: "3"
services:
  app:
    image: torb-app-ts
    build:
      context: ./webapp
      dockerfile: Dockerfile-nodejs
    links:
      - db
    #   - wd-server-fx2
    environment: # See : env.sh
      - DB_DATABASE=torb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=isucon
      - DB_PASS=isucon
    ports:
      - 8080:8080
    # volumes:
    #   - ./sampleProcessors:/app/processors
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=torb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=isucon
      - MYSQL_PASSWORD=isucon
      #- MYSQL_ROOT_HOST=%
  # wd-server-fx2:
  #   image: quay.io/wakaba/firefoxdriver:stable
  #   ports:
  #     - 10002:9516
